#!/bin/bash

# Project struct

export EVERYDAY_CODE_CONFIG_FOLDER="$(pwd)"
export EVERYDAY_CODE_BASE_FOLDER=$(dirname "$(dirname $EVERYDAY_CODE_CONFIG_FOLDER)")

export SOURCE_CODE_FOLDER=$EVERYDAY_CODE_BASE_FOLDER/src

export LEETCODE_CHALLENGES_FOLDER=$SOURCE_CODE_FOLDER/challenges/leetcode
export LEETCODE_CHALLENGES_TEMPLATE=$LEETCODE_CHALLENGES_FOLDER/template.cpp

export PLAYGROUND_FOLDER=$EVERYDAY_CODE_BASE_FOLDER/playground
export PLAYGROUND_FILE=$PLAYGROUND_FOLDER/playground.cpp;
export PLAYGROUND_TEMPLATE_FILE=$PLAYGROUND_FOLDER/playground.cxx;

export PLAYGROUND_EXAMPLES_FORLDER=$SOURCE_CODE_FOLDER/playground-examples

